[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "lifecyclelogging"
version = "2.1.0"
description = "A comprehensive logging utility for managing application lifecycle logs"
requires-python = ">=3.10"
license = { text = "MIT" }
readme = "README.md"
keywords = ["logging", "lifecycle", "debug"]
authors = [{ name = "Jon Bogaty", email = "jon@jonbogaty.com" }]
maintainers = [{ name = "Jon Bogaty", email = "jon@jonbogaty.com" }]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Typing :: Typed",
]
dependencies = [
    "rich>=13.7.1",
    "extended-data-types",
]

[project.urls]
Documentation = "https://extendeddata.dev"
Issues = "https://github.com/extended-data-library/extended-data-types/issues"
Source = "https://github.com/extended-data-library/extended-data-types"
Changelog = "https://github.com/extended-data-library/extended-data-types/blob/main/packages/lifecyclelogging/CHANGELOG.md"

[project.optional-dependencies]
tests = [
    "pytest>=8.2.2",
    "pytest-cov>=5.0.0",
    "pytest-xdist>=3.6.1",
    "coverage[toml]>=7.6.0",
    "hypothesis>=6.100.2",
]
docs = [
    "sphinx>=7.4.0",
    "sphinxawesome-theme>=5.2.0",
    "sphinx-autodoc2>=0.5.0",
    "sphinx-autodoc-typehints>=2.2.0",
    "sphinx-rtd-theme>=2.0.0",
    "myst-parser>=3.0.1",
    "docutils>=0.21.2",
]
typing = ["mypy>=1.10.1"]

[tool.uv.sources]
extended-data-types = { workspace = true }

[tool.hatch.build.targets.sdist]
exclude = [".github"]

[tool.hatch.build.targets.wheel]
packages = ["src/lifecyclelogging"]
exclude = [".github"]

[tool.pytest.ini_options]
addopts = ["-ra", "--strict-markers", "--strict-config"]
testpaths = "tests"
xfail_strict = true
filterwarnings = []

[tool.coverage.paths]
source = ["src/lifecyclelogging"]

[tool.coverage.run]
branch = true
parallel = true
source = ["lifecyclelogging"]
relative_files = true

[tool.coverage.xml]
output = "coverage.xml"

[tool.coverage.report]
show_missing = true
skip_covered = true
fail_under = 75
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if __name__ == '__main__':",
    "if TYPE_CHECKING:",
    "raise NotImplementedError",
    "raise ImportError",
    "except ImportError:",
    "pass",
]
